name: :octocat: 이슈 보고서
description: 이슈에 대한 보고서입니다
title: ":octocat:[이슈]: "
labels: [":octocat: 깃허브", ":dependabot: 봇"]
projects: ["github/1", "bot/1"]
assignees:
  - github
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        # test all 
        - 되나
        - [ ] test
