name: "⚜ 이슈 보고서"
description: "📋 이슈에 대한 보고서입니다"
title: "⚜ [이슈]: "
labels: ["🌑 깃허브", "🤖 봇"]
projects: ["github/1", "bot/1"]
assignees:
  - github
body:
  - type: markdown
    attributes:
      value: |
        # ℳ 마크다운 작성부분입니다.
        [마크다운을 지원합니다](#)
          - 다음줄에 기입이 가능하며
          - [ ] 깃 허브 마크다운으로 작동합니다
  - type: input
    id: input_id
    attributes:
      label: 📣 <질문 사항(텍스트 박스)>
      description: 💭 <옅은 설명글>
      placeholder: 🫧 <ex. 예시 문장>
    validations:
      required: true
  - type: textarea
    id: textarea_id
    attributes:
      label: 📣 <질문 사항(텍스트 어레이)>
      description: 💭 <옅은 설명글>
      placeholder: |
        🫧 <ex. 예시 지문>
        - [ ] 체크 1
        - [ ] 체크 2
      value: |
        - [ ] 체크 1
        - [ ] 체크 2
        - [ ] 체크 3
        - [ ] 더입력 ...
      render: ''
    validations:
      required: false
  - type: textarea
    id: textarea_id
    attributes:
      label: 📣 <질문 사항(텍스트 어레이)>
      description: 💭 <옅은 설명글>
      placeholder: |
        🫧 <ex. 예시 로그>
        % git push
      render: 'shell'
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      multiple: true
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
        - 1.0.4 (Edge)
      default: 1
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
      default: 1
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
