name: :octocat: 이슈 보고서
description: 이슈에 대한 보고서입니다
title: ":octocat:[이슈]: "
labels: [":octocat: 깃허브", ":dependabot: 봇"]
projects: ["github/1", "bot/1"]
assignees:
  - github
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        # test all 
        - 되나
        - [ ] test
# name: :octocat: 이슈 보고서
# description: 이슈에 대한 보고서입니다
# title: ":octocat:[이슈]: "
# labels: [":octocat: 깃허브", ":dependabot: 봇"]
# projects: ["github/1", "bot/1"]
# assignees:
# - github
# body:
#   - type: markdown
#     attributes:
#       value: |
#         # ℳ 마크다운 작성부분입니다.
#         마크다운을 지원합니다
#         - 다음줄에 기입이 가능하며
#         - [ ] 깃 허브 마크다운으로 작동합니다
 #  - type: input
 #    id: input_id
	# 	attributes:
	# 		label: 📣 <질문 사항(텍스트 박스)>
	# 		description: 💭 <옅은 설명글>
	# 		placeholder: 🫧 <ex. 예시 문장>
	# 	validations:
	# 		required: true
	# - type: textarea
	# 	id: textarea_id
	# 	attributes:
	# 		label: 📣 <질문 사항(텍스트 어레이)>
	# 		description: 💭 <옅은 설명글>
	# 		placeholder: 🫧 <ex. 예시 지문>
	# 		value: 
	# 		|
	# 			- [ ] 체크 1
	# 			- [ ] 체크 2
	# 			- [ ] 체크 3
	# 			- [ ] 더입력 ... 
	# 		render: bash
	# 	validations:
	# 		required: true
	# - type: dropdown
	# 	id: dropdown_id_sing
	# 	attributes:
	# 		label: 📣 <질문 사항(드롭 박스) 싱글>
	# 		description: 💭 <옅은 설명글>
	# 		multiple: false
	# 		options:
	# 			- <선택지1>
	# 			- <선택지2>
	# 			- <선택지3>
	# 		default: 0
	# 	validations:
	# 		required: true
	# - type: dropdown
	# 	id: dropdown_id_mult
	# 	attributes:
	# 		label: 📣 <질문 사항(드롭 박스) 멀티>
	# 		description: 💭 <옅은 설명글>
	# 		multiple: true
	# 		options:
	# 			- <선택지1>
	# 			- <선택지2>
	# 			- <선택지3>
	# 		default: 0
	# - type: checkboxes
	# 	id: checkboxes_id
	# 	attributes:
	# 		label: 📣 <질문 사항(체크 박스)>
	# 		description: 💭 <옅은 설명글>
	# 		options:
	# 			- label: <체크항목 1>
	# 				required: true
	# 			- label: <체크항목 2>
	# 				required: false
