name: "⚜ 이슈 보고서"
description: "📋 이슈에 대한 보고서입니다"
title: "⚜ [이슈]: "
labels: ["🌑 깃허브", "🤖 봇"]
projects: ["github/1", "bot/1"]
assignees:
  - github
body:
  - type: markdown
    attributes:
      value: |
        # ℳ 마크다운 작성부분입니다.
        [마크다운을 지원합니다](#)
          - 다음줄에 기입이 가능하며
          - [ ] 깃 허브 마크다운으로 작동합니다
  - type: input
    id: input_id
    attributes:
      label: 📣 <질문 사항(텍스트 박스)>
      description: 💭 <옅은 설명글>
      placeholder: 🫧 <ex. 예시 문장>
    validations:
      required: true
  - type: textarea
    id: textarea_id
    attributes:
      label: 📣 <질문 사항(텍스트 어레이)>
      description: 💭 <옅은 설명글>
      placeholder: |
        🫧 <ex. 예시 지문>
        - [ ] 체크 1
        - [ ] 체크 2
      value: |
        - [ ] 체크 1
        - [ ] 체크 2
        - [ ] 체크 3
        - [ ] 더입력 ...
      render: ''
    validations:
      required: false
  - type: textarea
    id: textarea_id_log
    attributes:
      label: 📣 <질문 사항(텍스트 어레이) log>
      description: 💭 <옅은 설명글>
      placeholder: |
        🫧 <ex. 예시 로그>
        % git push
        Enumerating objects: 7, done.
        Counting objects: 100% (7/7), done.
        Delta compression using up to 8 threads
        Compressing objects: 100% (3/3), done.
        Writing objects: 100% (3/3), 1.01 KiB | 1.01 MiB/s, done.
        Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
      render: 'shell'
    validations:
      required: true
  - type: dropdown
    id: dropdown_id_single
    attributes:
      label: 📣 <질문 사항(드롭 박스 싱글)>
      description: 💭 <옅은 설명글>
      multiple: false
      options:
        - <선택지1>
        - <선택지2>
        - <선택지3>
      default: 1
    validations:
      required: true
  - type: dropdown
    id: dropdown_id_mult
    attributes:
      label: 📣 <질문 사항(드롭 박스 멀티)>
      multiple: true
      options:
        - <선택지1>
        - <선택지2>
        - <선택지3>
  - type: checkboxes
    id: checkboxes_id
    attributes:
      label: 📣 <질문 사항(체크 박스)>
      description: 💭 <옅은 설명글>
      options:
        - label: <체크항목 1>
          required: true
        - label: <체크항목 2>
          required: true
        - label: <체크항목 2>
          required: false
