name: ":octocat: 이슈 보고서"
description: 이슈에 대한 보고서입니다
title: ":octocat:[이슈]: "
labels: [":octocat: 깃허브", ":dependabot: 봇"]
projects: ["github/1", "bot/1"]
assignees:
  - github
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        # test all 
        - 되나
        - [ ] test
  - type: input
    id: contact
    attributes:
      label: aa Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        - [ ] test
        - [ ] test2
        - [ ] test3
        ...
      render: ''
    validations:
      required: true
