name: ":octocat: 이슈 보고서"
description: ":clipboard: 이슈에 대한 보고서입니다"
title: ":octocat:[이슈]: "
labels: [":octocat: 깃허브", ":dependabot: 봇"]
projects: ["github/1", "bot/1"]
assignees:
  - github
body:
  - type: markdown
    attributes:
      value: |
        # ℳ 마크다운 작성부분입니다.
        [마크다운을 지원합니다](#)
          - 다음줄에 기입이 가능하며
          - [ ] 깃 허브 마크다운으로 작동합니다
  - type: input
    id: input_id
    attributes:
      label: 📣 <질문 사항(텍스트 박스)>
      description: 💭 <옅은 설명글>
      placeholder: 🫧 <ex. 예시 문장>
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        - [ ] test
        - [ ] test2
        - [ ] test3
        ...
      render: ''
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      multiple: true
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
        - 1.0.4 (Edge)
      default: 1
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
      default: 1
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
