name: "🎓 학습"
description: "학습에 설정에 대한 보고서입니다"
title: "🎓 Study: "
labels: ["🎓 학습"]
projects: ["liebespaar93/4"]
assignees:
  - liebespaar93
body:
  - type: markdown
    attributes:
      value: |
        # 학습 작성
        
        학습목록 추천 부분에 대한 링크
        
        - [🚀 준비중1](#)
        - [🚀 준비중2](#)
        
        ## 학습 작성 방법
          - 다음줄에 기입이 가능하며
          - 깃 허브 마크다운으로 작동합니다
  - type: input
    id: input_name
    attributes:
      label: 📣 학습 이름
      description: 💭 학습의 이름을 작성해 주세요
      placeholder: 🫧 <이름>
    validations:
      required: true
