name: <이모티콘> <이슈> 보고서
description: 이슈에 대한 보고서입니다
title: "<이모티콘>[<이슈>]: "
labels: ["<이모티콘> <라벨1>", "<이모티콘> <라벨2>"]
projects: ["<아이디>/<프로젝트번호1>", "<아이디>/<프로젝트번호2>"]
assignees:
  - <담당자 아이디>
body:
  - type: markdown
    attributes:
      value: |
        # ℳ 마크다운 작성부분입니다.
        [마크다운을 지원합니다](#)
        - 다음줄에 기입이 가능하며
        - [ ] 깃 허브 마크다운으로 작동합니다

  - type: input
    id: < 작성 = [ 영문 | '-' | '_' ] ? '<label for="작성"> </label>'" >
    attributes:
      label: 📣 <질문 사항(텍스트 박스)>
      description: 💭 <옅은 설명글>
      placeholder: 🫧 <ex. 예시 문장>
    validations:
      required: < 필수 옵션 = true | false >

  - type: textarea
    id: < 작성 = [ 영문 | '-' | '_' ] ? '<label for="작성"> </label>'" >
    attributes:
      label: 📣 <질문 사항(텍스트 어레이)>
      description: 💭 <옅은 설명글>
      placeholder: 🫧 <ex. 예시 지문>
      value: 
      |
        - [ ] 체크 1
        - [ ] 체크 2
        - [ ] 체크 3
        - [ ] 더입력 ... 
      render: < 코드타입 = '' | bash | css | html ... ? ''는 마크다운 >
    validations:
      required: < 필수 옵션 = true | false >

  - type: dropdown
    id: < 작성 = [ 영문 | '-' | '_' ] ? '<label for="작성"> </label>'" >
    attributes:
      label: 📣 <질문 사항(드롭 박스)>
      description: 💭 <옅은 설명글>
      multiple: < 멀티 옵션 = true | false >
      options:
        - <선택지1>
        - <선택지2>
        - <선택지3>
      default: < 기본 선택 인덱스 = [0-9]* ? 필수 옵션일 경우 필요 >
    validations:
      required: < 필수 옵션 = true | false ? 멀티옵션 true 면작동안함>

  - type: checkboxes
    id: < 작성 = [ 영문 | '-' | '_' ] ? '<label for="작성"> </label>'" >
    attributes:
      label: 📣 <질문 사항(체크 박스)>
      description: 💭 <옅은 설명글>
      options:
        - label: <체크항목 1>
          required: < 필수 옵션 = true | false ? 선택시 채크항목 다 채크 후 승인 >
        - label: <체크항목 1>
          required: < 필수 옵션 = true | false ? 선택시 채크항목 다 채크 후 승인 >
