name: "🗃️ 템플릿 보고서"
description: "템플릿에 설정에 대한 보고서입니다"
title: "🗃️ [템플릿]: "
labels: ["📝 문서", "🗃️ 템플릿"]
projects: ["liebespaar93/4"]
assignees:
  - liebespaar93
body:
  - type: input
    id: input_name
    attributes:
      label: 📣 템플릿 이름
      description: 💭 템픞릿의 이름을 작성해 주세요
      placeholder: 🫧 <이름>
    validations:
      required: true
