name: "🗃️ 템플릿 보고서"
description: "템플릿에 설정에 대한 보고서입니다"
title: "🗃️ [템플릿]: "
labels: ["📝 문서", "🗃️ 템플릿"]
projects: ["liebespaar93/4"]
assignees:
  - liebespaar93
body:
  - type: markdown
    attributes:
      value: |
        # 템플릿 작성
        가이드라인 [🚀 링크](https://gist.github.com/liebespaar93/0590fb2eb01aeb38d8f57a25933b8f65#file-simple_template-yml) 를 확인해 주세요
        ## 템플릿 작성 방법
          - 다음줄에 기입이 가능하며
          - 깃 허브 마크다운으로 작동합니다
  - type: input
    id: input_name
    attributes:
      label: 📣 템플릿 이름
      description: 💭 템픞릿의 이름을 작성해 주세요
      placeholder: 🫧 <이름>
    validations:
      required: true
  - type: textarea
    id: textarea_description
    attributes:
      label: 📣 템플릿 생성 이유
      description: 💭 템플릿 생성 이유을 적어주세요
      placeholder: |
        🫧 <템플릿 생성 이유>
        1. <이유>
        2. <이유>
      render: ''
    validations:
      required: false
  - type: textarea
    id: textarea_work
    attributes:
      label: 📣 작업 리스트
      description: 💭 작업에 필요한 목록 작성
      placeholder: |
        🫧 <ex. 예시 지문>
        - [ ] 체크 1
        - [ ] 체크 2
      value: |
        - [ ] 체크 1
        - [ ] 체크 2
        - [ ] 체크 3
        - [ ] 더입력 ...
      render: ''
    validations:
      required: true
  - type: checkboxes
    id: checkboxes_id
    attributes:
      label: 📣 작성자 동의
      description: 💭 작성자 동의서
      options:
        - label: 📌 작성자는 모든 작업에 대한 정보가 공개됨을 동의함니까?
          required: true
